export { default as SearchWhiteIcon } from '../../public/icons/search.svg'
export { default as PersonFillWhiteIcon } from '../../public/icons/person-fill-white.svg'
export { default as XLgWhiteIcon } from '../../public/icons/x-lg-white.svg'
export { default as ListWhiteIcon } from '../../public/icons/list-white.svg'
export { default as ArrowLeftSquareWhiteIcon } from '../../public/icons/arrow-left-square-white.svg'
